import 'dart:math';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:ochanya_gili/features/payment/domain/models/payment_models.dart';

abstract class PaymentProvider {
  Future<PaymentInitResult> initializePayment({
    required String orderNumber,
    required double amount,
    required String email,
    required String customerName,
    Map<String, dynamic>? metadata,
  });

  Future<PaymentVerificationResult> verifyPayment({
    required String orderNumber,
    required String reference,
    required double amount,
    Map<String, dynamic>? metadata,
  });
}

class PaystackPaymentProvider implements PaymentProvider {
  final SupabaseClient _client;

  PaystackPaymentProvider(this._client);

  @override
  Future<PaymentInitResult> initializePayment({
    required String orderNumber,
    required double amount,
    required String email,
    required String customerName,
    Map<String, dynamic>? metadata,
  }) async {
    // Generate authoritative unique transaction reference for atelier tracking
    final randomSuffix = Random().nextInt(9999).toString().padLeft(4, '0');
    final reference = 'OG-TX-${DateTime.now().millisecondsSinceEpoch}-$randomSuffix';

    // In a live production environment with Supabase Edge Functions or Paystack Checkout,
    // the authorization URL is generated by the server. We prepare the reference for modal or web checkout.
    return PaymentInitResult(
      reference: reference,
      orderNumber: orderNumber,
      amount: amount,
      authorizationUrl: 'https://checkout.paystack.com/$reference',
      accessCode: reference,
    );
  }

  @override
  Future<PaymentVerificationResult> verifyPayment({
    required String orderNumber,
    required String reference,
    required double amount,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      // MASTER QUALITY GATE RULE 5 & 10:
      // Client code NEVER directly executes "UPDATE orders SET status = 'paid'".
      // Verification is delegated to the server-side RPC verify_and_mark_order_paid.
      final res = await _client.rpc('verify_and_mark_order_paid', params: {
        'p_order_number': orderNumber,
        'p_payment_reference': reference,
        'p_provider': 'paystack',
        'p_amount': amount,
        'p_metadata': metadata ?? {},
      });

      final data = res as Map<String, dynamic>;
      final isSuccess = data['success'] as bool? ?? false;

      if (isSuccess) {
        return PaymentVerificationResult(
          isSuccessful: true,
          reference: reference,
          orderNumber: orderNumber,
          amount: amount,
          channel: 'paystack_inline',
          message: 'Payment verified and confirmed by server',
          paidAt: DateTime.now(),
          orderId: data['order_id'] as String?,
        );
      } else {
        return PaymentVerificationResult(
          isSuccessful: false,
          reference: reference,
          orderNumber: orderNumber,
          amount: amount,
          message: data['error'] as String? ?? 'Payment verification failed',
        );
      }
    } catch (e) {
      return PaymentVerificationResult(
        isSuccessful: false,
        reference: reference,
        orderNumber: orderNumber,
        amount: amount,
        message: 'Server verification error: $e',
      );
    }
  }
}

final paymentProviderProvider = Provider<PaymentProvider>((ref) {
  return PaystackPaymentProvider(Supabase.instance.client);
});
